# Site
repository: diodz/diodz.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Diego Andres Diaz
title: Research Scientist
email: diegodiaz@uchicago.edu
website: diodz.github.io
github: metadata

# Social links
twitter_username:
github_username:  diodz
stackoverflow_username: ""
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: diego-a-diaz-24754191/
xing_username:
pinterest_username:
youtube_username:
googleplus_username:
orcid_username:

# Additional icon links
additional_links:
- title: Test link
  icon: fa-ello
  url: diodz.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/pic.jpeg
about_content: > # this means to ignore newlines until the next config item.
  Quantitative macroeconomist with 7+ years of research experience in dynamic programming, and core econometric methods applied in economic growth of developing economies and education policy

  Strong background in python with an emphasis in quantitative economic modelling and machine learning methods

  Three papers published or forthcoming in peer-reviewed academic journals, and other three under revision

  Experience in written and oral communication to various audiences from academics and students to business managers through review/editing and oral presentations

  Experience in management through hiring and training 15 students to be research assistants of faculty members in a business school (Escuela de Negocios, Universidad del Desarrollo)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Skills Section
# skills_title: Skills #(Use this to override about education section title)

# Publication Section
# publication_title: Publication #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Teaching Section
# teaching_title: Teaching #(Use this to override about experience section title)

# Conference Section
# conference_title: Conference #(Use this to override about experience section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: > # this means to ignore newlines until the next config item.
  Experience in management through hiring and training 15 students to be research assistants of faculty members in a business school (Escuela de Negocios, Universidad del Desarrollo)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

data_dir: /_data

exclude:
  - vendor

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages
